name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.10.0' # Replace 'stable' with a specific version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
